on:
  pull_request:
    branches: [ master ]

jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install dependencies
        working-directory: ./functions
        run: yarn install
      - name: Run lint
        working-directory: ./functions
        run: yarn lint
      - name: Run tests
        working-directory: ./functions
        run: yarn test
